[workspace]
resolver = "2"
members = ["microservices/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Yurii Musolov <yurii.musolov@gmail.com>"]

[workspace.dependencies]
anyhow = "1.0.94"
axum = "0.7.7"
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
sha2 = "0.10.8"
sqlx = { version = "0.8.2", features = [
  "postgres",
  "runtime-tokio",
  "runtime-tokio-rustls",
  "time",
  "uuid",
] }
tokio = { version = "1.41.0", features = ["full"] }
tower-http = { version = "0.6.1", features = ["cors", "fs", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
