networks:
  default:

volumes:
  postgres:

services:

  postgres:
    image: "postgres:17.2"
    container_name: "patisson_postgres"
    restart: always
    ports:
      - "${patisson__postgres__port:-0}:5432"
    volumes:
      - ./.postgres:/docker-entrypoint-initdb.d
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "${PATISSON__POSTGRES__PASSWORD}"
      POSTGRES_USER: "${PATISSON__POSTGRES__USER}"

  auth:
    build:
      context: "."
      target: "auth"
    image: "patisson-auth"
    container_name: "patisson_auth"
    restart: always
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "${patisson__auth__port:-0}:3000"
    environment:
      PATISSON__AUTH__DATABASE_URL: "postgres://auth_user:auth_pass@postgres:5432/auth_db"
      PATISSON__AUTH__ADDR: "auth:3000"
    command: [ "serve" ]
