name: patisson-api

networks:
  default:

volumes:
  postgres:

services:

  postgres:
    image: "postgres:17.4-alpine3.21"
    container_name: "patisson_postgres"
    restart: always
    ports:
      - "${patisson__postgres__port:-0}:5432"
    volumes:
      - ./.postgres:/docker-entrypoint-initdb.d
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "${PATISSON__POSTGRES__PASSWORD}"
      POSTGRES_USER: "${PATISSON__POSTGRES__USER}"

  setup:
    build:
      context: "."
      target: "setup"
    image: "patisson-setup"
    container_name: "patisson_setup"
    restart: no
    depends_on:
      postgres:
        condition: service_started
    environment:
      # TODO: Use the DBA username and password for DBs migration.
      PATISSON__AUTH__DATABASE_URL: "postgres://auth_user:auth_pass@postgres:5432/auth_db"
    command: [ "migrate" ]

  auth:
    build:
      context: "."
      target: "auth"
    image: "patisson-auth"
    container_name: "patisson_auth"
    restart: always
    depends_on:
      postgres:
        condition: service_started
      setup:
        condition: service_completed_successfully
    ports:
      - "${patisson__auth__port:-0}:3000"
    environment:
      PATISSON__AUTH__DATABASE_URL: "postgres://auth_user:auth_pass@postgres:5432/auth_db"
      PATISSON__AUTH__DATABASE_MAX_CONNECTION: 10
      PATISSON__AUTH__HTTP_ADDR: "auth:3000"
      JWT_SECRET: "${JWT_SECRET}"
    command: [ "serve" ]

  provider:
    build:
      context: "."
      target: "provider"
    image: "patisson-provider"
    container_name: "patisson_provider"
    restart: always
    ports:
      - "${patisson__provider__http_port:-0}:3000"
    environment:
      PATISSON__PROVIDER__HTTP_ADDR: "provider:3000"
    command: [ "serve" ]
