[package]
name = "bybit-sdk"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
reqwest.workspace = true
serde-aux.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
