[package]
name = "analytics"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "calc"
harness = false
