[package]
name = "provider"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
axum.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
